%YAML:1.0
#> Dataset
dataset_dir: /home/chchien/datasets/TUM-RGBD/
sequence_name: rgbd_dataset_freiburg1_desk/
dataset_type: tum

#> Camera calibration matrix. Choose either fr1, fr2, or fr3.
#> freiburg1
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 318.6
camera.cy: 255.3

#> freiburg2
#camera.fx: 525.0
#camera.fy: 525.0
#camera.cx: 319.5
#camera.cy: 239.5

#> freiburg3
#camera.fx: 520.9
#camera.fy: 521.0
#camera.cx: 325.1
#camera.cy: 249.7


